#!/system/bin/sh
# call userinit.sh if present in /data/local

if [ -e /data/local/userinit.sh ];
then
   log -p i -t userinit "Executing /data/local/userinit.sh";
   /system/bin/sh /data/local/userinit.sh;
   setprop razer.userinit.active 1;
fi;

if [ -d /data/local/userinit.d ];
then
   busybox run-parts /data/local/userinit.d;
   setprop razer.userinit.active 1;
fi;
