#!/system/bin/sh

LS=/data/L_Speed/Logs/01Seeder.log

busybox rm -f $LS
busybox touch $LS

if pgrep qrngd > /dev/null; then
  echo "qrngd already running! Seeder will not be started!" >> $LS
  exit 1
fi

if [ -e /system/bin/qrngd -o -e /system/xbin/qrngd ]; then
  echo "qrngd found in /system! Seeder will not be started!" >> $LS
  exit
fi

rngd -t 2 -T 1 -s 256 --fill-watermark=80%
sleep 2
echo -8 > /proc/$(pgrep rngd)/oom_adj
renice 5 `pidof rngd`
