# Versioning System For RazerRom
# RazerRom RELEASE VERSION
RAZER_VERSION_MAJOR = 3
RAZER_VERSION_MINOR = 6
RAZER_VERSION_MAINTENANCE =

VERSION := $(RAZER_VERSION_MAJOR).$(RAZER_VERSION_MINOR)$(RAZER_VERSION_MAINTENANCE)

# Set RAZER_BUILDTYPE
ifdef RAZER_NIGHTLY
    RAZER_BUILDTYPE := NIGHTLY
endif
ifdef RAZER_EXPERIMENTAL
    RAZER_BUILDTYPE := EXPERIMENTAL
endif
ifdef RAZER_RELEASE
    RAZER_BUILDTYPE := RELEASE
endif
# Set Unofficial if no buildtype set (Buildtype should ONLY be set by RAZER Dev!)
ifdef RAZER_BUILDTYPE
else
    RAZER_BUILDTYPE := OFFICIAL
    RAZER_VERSION_MAJOR := 3
    RAZER_VERSION_MINOR := 6
endif

# Set RazerRom version
ifdef RAZER_RELEASE
    RAZER_VERSION := RazerRom-v$(VERSION) 
else
    RAZER_VERSION := RazerRom-v$(VERSION)-$(RAZER_BUILD)-$(RAZER_BUILDTYPE)-$(shell date +%Y%m%d-%H%M)
endif

RAZER_DISPLAY_VERSION := $(VERSION)
RAZER_DISPLAY_BUILDTYPE := $(RAZER_BUILDTYPE)

PRODUCT_PROPERTY_OVERRIDES += \
  ro.modversion=$(RAZER_DISPLAY_VERSION) \
  ro.razer.display.version=$(RAZER_DISPLAY_VERSION) \
  ro.razer.display.buildtype=$(RAZER_DISPLAY_BUILDTYPE)
