#!/system/bin/sh

LS=/data/L_Speed/Logs/03Ram_manager.log

busybox rm -f $LS
busybox touch $LS

echo "# L Speed log " | tee -a $LS
echo "" | tee -a $LS
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Tweaking minfree values & adj lowmem values..." | tee -a $LS;

busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system


# ADJ Values
busybox chmod 644 /sys/module/lowmemorykiller/parameters/adj;

echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj;

busybox chmod 444 /sys/module/lowmemorykiller/parameters/adj;


# Minfree Values 

mem=`free|grep Mem | awk '{print $2}'`;
busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree;

if [ "$mem" -lt 256000 ];then
    echo "2048,3072,7168,7680,8960,12800" >/sys/module/lowmemorykiller/parameters/minfree;
elif [ "$mem" -lt 512000 ];then
    echo "1024,2048,4096,8192,12288,16384" > /sys/module/lowmemorykiller/parameters/minfree;	
elif [ "$mem" -lt 768000 ];then
    echo "2048,3072,4096,8960,14336,16384" >/sys/module/lowmemorykiller/parameters/minfree;
elif [ "$mem" -lt 1024000 ];then
	echo "2560,4096,6144,12288,14336,18432" > /sys/module/lowmemorykiller/parameters/minfree;
else 
	echo "3755,6144,9387,14336,17284,21240" > /sys/module/lowmemorykiller/parameters/minfree;
fi;

busybox chmod 444 /sys/module/lowmemorykiller/parameters/minfree;


busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager successfully applied.." | busybox tee -a $LS
